### ISSUE TITLE
No NVT available

### ISSUE THREAD

**Issue by thefactor82** [peektwice/gvm-ansible#4]
Hi, using your role to install gvm, when it finish on my platform I cannot do any scans because
![image](https://user-images.githubusercontent.com/30239971/87289268-b5419c00-c4fc-11ea-83cb-2039d3f8fed4.png)

Do I have maybe some sync to launch manually?

**Comment by peektwice** [comment]
Yes. Currently, the tasks.yml file is set to "ignore_errors: yes" on the greenbone-nvt-sync, greenbone-certdata-sync, and greenbone-scapdata-sync tasks. This is because on my test system, I've been having issues with it syncing with the community feed. This is probably a network issue, as Greenbone only allows one connection at a time to the feed sync servers, and something is causing it to appear as though a previous connection is still open with a new rsync connection is attempted.

If you manually run greebone-nvt-sync, greenbone-certdata-sync, and greenbone-scapdata-sync, this should resolve the issue. You should also wait for gvmd to finish loading the NVTs, certdata, and scapdata, as this can take some time.

**Comment by peektwice** [comment]
Just tested this, and my findings are as yours are. Even thought all of the sync processes succeeded, I get the same message.

**Comment by peektwice** [comment]
I do see NVTs available under Administration->Feed Status. And I now do not have the "No NVTs available" message. It appears that gvmd is still updating the nvt cache. Might this be the issue?

![Screen Shot 2020-07-13 at 4 39 03 PM](https://user-images.githubusercontent.com/40467862/87356340-868ceb00-c527-11ea-80c9-877b64ac3730.png)

**Comment by peektwice** [comment]
I saw in /opt/gvm/var/log/ospd-openvas.log the dreaded "Error creating feed lock file. Trying again later..." message. So I stopped the ospd-openvas service, removed the /opt/gvm/var/run/eed-update.lock, and restarted the ospd-openvas service. This seems to have corrected the issue. Now, how to automatically get it working.

**Comment by thefactor82** [comment]
Mmmm, I think I have some major problem...
greenbone-nvt-sync and all other syncs were launched manually, and they finished succesfully.
Then I see also the "Error creating feed lock file. Trying again later..." so I've tried to stop and restart as you did... But no good news, I still have 0 NVT in list (and gvmd process doesn't says anything about Reloading NVTs.

In addiction: The Openvas Default service scanner is not available...
Could not connect to Scanner at /opt/gvm/var/run/ospd.sock
manage_update_nvt_cache_osp: failed to connect to /opt/gvm/var/run/ospd.sock

**Comment by peektwice** [comment]
After stopping the ospd-openvas service, did you remove the lock file at /opt/gvm/var/run/feed-update.lock prior to restarting ospd? OSPD won't create the unix socket file until it has finished starting up, and it won't start up if the feed-update.lock file is still there.

**Comment by thefactor82** [comment]
Yep, I've removed it

**Comment by peektwice** [comment]
Sorry if I'm asking obvious questions.

You've removed the lock file, re-ran greenbone-nvt-sync, made sure it completed succesfully (check for /opt/gvm/var/lib/openvas/plugins/plugin_feed_info.inc). Run "openvas -u" to tell gvmd to update itself. Then make sure the lock file is still gone. Start ospd-openvas service, wait for a while, make sure the lockfile is gone and that you now have an ospd.sock file?

There's a lot of moving parts that are interrelated. The feed update will create a lock file, and ospd will not complete startup if it's there. gvmd will not connect to ospd if the Unix socket file is not there, and ospd will not create the Unix socket file until it is able to complete startup (which is dependent on the lock file being gone.) And somewhere in all of this, gvmd needs to know about the feed being updated, so it can update the NVT cache.

**Comment by thefactor82** [comment]
Sorry for late response, and thankyou for your explanation...
Currently:
stopped ospd-openvas service
removed /opt/gvm/var/run/feed-update.lock
then as gvm run /opt/gvm/bin/greenbone-nvt-sync
seems succesfully completed:

```
cat /opt/gvm/var/lib/openvas/plugins/plugin_feed_info.inc
# Copyright (C) 2020 Greenbone Networks GmbH
#
# SPDX-License-Identifier: GPL-2.0-or-later
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.

PLUGIN_SET = "202007151130";
PLUGIN_FEED = "Greenbone Community Feed";
FEED_VENDOR = "Greenbone Networks GmbH";
FEED_HOME = "http://www.openvas.org/openvas-nvt-feed.html";
FEED_NAME = "GCF";
```


but feed-update.lock is now present...

**Comment by peektwice** [comment]
Then you're getting the NVT feed, so that's good. The greenbone-scapdata-sync and greenbone-certdata-sync process may also be creating the lock file. In addition, while oscp-openvas is starting, you may see a lock file until it completes and updates gvmd's cache. At least that was my experience. It took a few minutes for that process to complete and for the system to start all the way up. Once that was done, the lock file went away and I was able to perform scans.

**Comment by thefactor82** [comment]
I have done nothing but /opt/gvm/bin/greenbone-nvt-sync  and the lock file is present. I have to wait for it to disappear? Or can I try something else? I didn't restarted the oscp-openvas service...

**Comment by peektwice** [comment]
Hmm... it should have deleted itself. Go ahead and delete it, then run "openvas -u" to update the gvmd cache. Make sure that the lock file is still gone after that. When that's done, you should be able to start oscp-openvas service.

**Comment by thefactor82** [comment]
Deleted,
run openvas -u,
started oscp-openvas
and feed-update.lock is again here!

(I don't know if I have to smile or to cry... I'll opt for the first one :-) )

**Comment by peektwice** [comment]
What does /opt/gvm/var/log/gvm/ospd-openvas.log say?

**Comment by thefactor82** [comment]
Absolutely nothing...
But in my processes I see
` ps ax | grep gvm
   1032 ?        Sl     0:00 /opt/gvm/sbin/gsad --mlisten=0.0.0.0 --mport=9390 --drop-privileges=gvm --ssl-certificate=/etc/ssl/certs/gvm.crt --ssl-private-key=/etc/ssl/certs/gvm.key
   2737 ?        SL     0:33 gvmd: Waiting for incoming connections
   2760 ?        Ss     1:04 postgres: gvm gvmd [local] idle
 111127 ?        Sl     4:48 /usr/bin/python3 /opt/gvm/bin/ospd-openvas --pid-file /opt/gvm/var/run/ospd-openvas.pid --unix-socket /opt/gvm/var/run/ospd.sock --log-file /opt/gvm/var/log/gvm/ospd-openvas.log --lock-file-dir /opt/gvm/var/run
 113272 ?        S      0:00 gvmd: Reloading NVTs
 113274 ?        S      0:00 gvmd: OSP: Updating NVT cache
 113275 ?        Ss     0:00 postgres: gvm gvmd [local] idle
 113289 pts/0    S+     0:00 grep --color=auto gvm
`

"Reloading NVTs"... Maybe I have to wait?

**Comment by peektwice** [comment]
Yeah, let's give it a while and see what happens. In the original greenbone-nvt-sync script, I see that it has been changed to use "flock" for advisory record locking on the feed lock file. This *should* automatically remove the lock when it's done. https://github.com/greenbone/openvas/blob/master/tools/greenbone-nvt-sync.in

**Comment by peektwice** [comment]
It looks like the latest changes in the greenbone-nvt-sync script cause the feed lock file to be left behind, no matter what you do. It used to clean up after itself, but this might be an issue with the parent source. I'll raise it and see.

https://github.com/greenbone/openvas/commit/dd54c9bb1e6220a4eab9e2fd804a1c0a24dc51a7?diff=unified

**Comment by peektwice** [comment]
[Here](https://github.com/greenbone/ospd-openvas/blob/291f9d88835c0f19876efa531f1c64ed0f55265b/ospd_openvas/lock.py#L49), it looks like ospd-openvas only needs to be able to open the lock file for writing. I'm changing version numbers to the x.0.1 versions so that I'll get the latest updates of all the code and make sure that the locks are being handled in a consistent fashion. Stay tuned.

**Comment by thefactor82** [comment]
ook thank you very much!!

**Comment by peektwice** [comment]
Out of curiosity, if you run the playbook start to finish, login to your vm as root, what does 'lslocks' show?
I'm running the playbook right now, waiting for the sync to finish, and see what happens.

**Comment by thefactor82** [comment]
if I run the playbook from start to finish, the greenbone-scap-sync fails. So I've splitted it in 2 playbooks, and I have launched manually the 3 sync commands and the openvas -u 
But, If you want, I can try it in a single shot. Tomorrow...

**Comment by peektwice** [comment]
No worries. It appears that the latest version of gvmd has unified the sync scripts into a single greenbone-gvmd-feed-sync script. I'll need to make some updates and then push them to the repo. It will take me a couple days, probably.

**Comment by peektwice** [comment]
Ok, by using the HEAD version of the various Greenbone git repos, I was able to make the sync jobs work and remove the various advisory locks. (/opt/gvm/var/run/feed-update.lock, /tmp/gvm-sync-cert, and /tmp/gvm-sync-scap). But now the issue I'm having is an error on the login screen. I'm successfully able to authenticate to GSAD, but I get a "Network error: Unexpected token < in JSON at position 0" error. That usually indicates that you're getting HTML back, where it's expecting JSON. So I'll go back and figure out what version flags I should use instead of "HEAD" to make it stable.

**Comment by peektwice** [comment]
Okay, one more test for today, then I'm gonna take a break. Right now, I am running it from start to finish. Even to the point of doing a "vagrant box remove" prior to running "vagrant up".

**Comment by peektwice** [comment]
Last run through went all the way. Shows the correct default scanner in the console, as well as fully updated feeds. ospd-openvas starts properly, gvmd starts properly, and gsad does as well. Let me know your results, and if you find the same, I'll close this issue. Good night.

**Comment by peektwice** [comment]
I did get one error in the gvmd.log file ```relation "cert_bund_advs" does not exist``` but I was able to successfully create tasks and targets and start the scan tasks. I was also able to get scan results, so it looks like everything is working.

**Comment by thefactor82** [comment]
Ok, just to keep you informed...
Cloned repo. Launched Ansible, first run stuck on the greenbone-scapdata-sync step (as always).
I've done nothing manually on the machine, re-launched the playbook, that finished correctly.
Now logging in the web console I can see the NVTs correctly, but there is an "unknown error" message in every page (but maybe I have to wait...)
However, this is now my process list:
 ps ax | grep gvm
 589549 ?        Sl     3:58 /usr/bin/python3 /opt/gvm/bin/ospd-openvas --pid-file /opt/gvm/var/run/ospd-openvas.pid --unix-socket /opt/gvm/var/run/ospd.sock --log-file /opt/gvm/var/log/gvm/ospd-openvas.log --lock-file-dir /opt/gvm/var/run
 589721 ?        SL     0:04 gvmd: Waiting for incoming connections
 589742 ?        Ss     0:00 gpg-agent --homedir /opt/gvm/var/lib/gvm/gvmd/gnupg --use-standard-socket --daemon
 589751 ?        Ss     0:13 postgres: gvm gvmd [local] idle
 589760 ?        S      1:44 gvmd: Syncing SCAP: Updating placeholders
 589764 ?        Ss    11:11 postgres: gvm gvmd [local] UPDATE
 590160 ?        Sl     0:00 /opt/gvm/sbin/gsad --mlisten=0.0.0.0 --mport=9390 --drop-privileges=gvm
 590161 ?        Sl     0:00 /opt/gvm/sbin/gsad --mlisten=0.0.0.0 --mport=9390 --drop-privileges=gvm
 591679 ?        S      0:00 gvmd: Reloading NVTs
 591682 ?        S      0:00 gvmd: OSP: Updating NVT cache
 591684 ?        Ss     0:00 postgres: gvm gvmd [local] idle
 591696 pts/0    R+     0:00 grep --color=auto gvm

gvmd says that is reloading nvts, updating cache, and syncing SCAP.
It is correct that I have 2 gsad processes running?

**Comment by peektwice** [comment]
Ok, let's be really clear on this. Syncing the NVTs, the Cert data, and the SCAP data takes at least two hours to complete. Even then, once the rsync process has completed, it takes quite a few minutes for gvmd to update SCAP and NVT data. It's a looooooonnggg time. A seriously long time. But it would be so even if you hand built the system, because it just takes that long for the rsync process to finish the first time around. In subsequent rsync processes, it's a lot less time, because it's only picking up the changes or deltas.

Once all of this has completed, yes it's quite normal for there to be more than one gsad process or more than one openvas or gvmd process. If you us 'ps -ef' instead of 'ps ax' to see this, you can see that those are related processes. One is the parent process of the other.

Since your rsync is complete and you do in fact see that the NVT cache is being updated, I'm going to close this issue. If you have additional issues, please raise them here.
